// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/vue-query';

import { client } from '../client.gen';
import { type Options, ordersIndex, ordersShow, ordersStore, productsIndex, productsShow } from '../sdk.gen';
import type { OrdersIndexData, OrdersIndexError, OrdersIndexResponse, OrdersShowData, OrdersShowResponse, OrdersStoreData, OrdersStoreError, OrdersStoreResponse, ProductsIndexData, ProductsIndexError, ProductsIndexResponse, ProductsShowData, ProductsShowError, ProductsShowResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const ordersIndexQueryKey = (options?: Options<OrdersIndexData>) => createQueryKey('ordersIndex', options);

/**
 * Display a listing of the resource
 */
export const ordersIndexOptions = (options?: Options<OrdersIndexData>) => queryOptions<OrdersIndexResponse, OrdersIndexError, OrdersIndexResponse, ReturnType<typeof ordersIndexQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ordersIndex({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ordersIndexQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const ordersIndexInfiniteQueryKey = (options?: Options<OrdersIndexData>): QueryKey<Options<OrdersIndexData>> => createQueryKey('ordersIndex', options, true);

/**
 * Display a listing of the resource
 */
export const ordersIndexInfiniteOptions = (options?: Options<OrdersIndexData>) => infiniteQueryOptions<OrdersIndexResponse, OrdersIndexError, InfiniteData<OrdersIndexResponse>, QueryKey<Options<OrdersIndexData>>, number | null | Pick<QueryKey<Options<OrdersIndexData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<OrdersIndexData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await ordersIndex({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ordersIndexInfiniteQueryKey(options)
});

export const ordersStoreMutation = (options?: Partial<Options<OrdersStoreData>>): UseMutationOptions<OrdersStoreResponse, OrdersStoreError, Options<OrdersStoreData>> => {
    const mutationOptions: UseMutationOptions<OrdersStoreResponse, OrdersStoreError, Options<OrdersStoreData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ordersStore({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ordersShowQueryKey = (options: Options<OrdersShowData>) => createQueryKey('ordersShow', options);

export const ordersShowOptions = (options: Options<OrdersShowData>) => queryOptions<OrdersShowResponse, DefaultError, OrdersShowResponse, ReturnType<typeof ordersShowQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ordersShow({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ordersShowQueryKey(options)
});

export const productsIndexQueryKey = (options?: Options<ProductsIndexData>) => createQueryKey('productsIndex', options);

/**
 * Display a listing of the resource
 */
export const productsIndexOptions = (options?: Options<ProductsIndexData>) => queryOptions<ProductsIndexResponse, ProductsIndexError, ProductsIndexResponse, ReturnType<typeof productsIndexQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await productsIndex({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: productsIndexQueryKey(options)
});

export const productsIndexInfiniteQueryKey = (options?: Options<ProductsIndexData>): QueryKey<Options<ProductsIndexData>> => createQueryKey('productsIndex', options, true);

/**
 * Display a listing of the resource
 */
export const productsIndexInfiniteOptions = (options?: Options<ProductsIndexData>) => infiniteQueryOptions<ProductsIndexResponse, ProductsIndexError, InfiniteData<ProductsIndexResponse>, QueryKey<Options<ProductsIndexData>>, number | null | Pick<QueryKey<Options<ProductsIndexData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ProductsIndexData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await productsIndex({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: productsIndexInfiniteQueryKey(options)
});

export const productsShowQueryKey = (options: Options<ProductsShowData>) => createQueryKey('productsShow', options);

/**
 * Display the specified resource
 */
export const productsShowOptions = (options: Options<ProductsShowData>) => queryOptions<ProductsShowResponse, ProductsShowError, ProductsShowResponse, ReturnType<typeof productsShowQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await productsShow({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: productsShowQueryKey(options)
});
