// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { OrderCancelData, OrderCancelErrors, OrderCancelResponses, OrderCompleteData, OrderCompleteErrors, OrderCompleteResponses, OrderCreateData, OrderCreateErrors, OrderCreateResponses, OrdersIndexData, OrdersIndexErrors, OrdersIndexResponses, OrdersShowData, OrdersShowResponses, OrdersStoreData, OrdersStoreErrors, OrdersStoreResponses, ProductSearchData, ProductSearchErrors, ProductSearchResponses, ProductsIndexData, ProductsIndexErrors, ProductsIndexResponses, ProductsShowData, ProductsShowErrors, ProductsShowResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Display a listing of the resource
 */
export const ordersIndex = <ThrowOnError extends boolean = false>(options?: Options<OrdersIndexData, ThrowOnError>) => (options?.client ?? client).get<OrdersIndexResponses, OrdersIndexErrors, ThrowOnError>({ url: '/api/orders', ...options });

export const ordersStore = <ThrowOnError extends boolean = false>(options: Options<OrdersStoreData, ThrowOnError>) => (options.client ?? client).post<OrdersStoreResponses, OrdersStoreErrors, ThrowOnError>({
    url: '/api/orders',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const ordersShow = <ThrowOnError extends boolean = false>(options: Options<OrdersShowData, ThrowOnError>) => (options.client ?? client).get<OrdersShowResponses, unknown, ThrowOnError>({ url: '/api/orders/{orderId}', ...options });

export const orderCreate = <ThrowOnError extends boolean = false>(options: Options<OrderCreateData, ThrowOnError>) => (options.client ?? client).post<OrderCreateResponses, OrderCreateErrors, ThrowOnError>({
    url: '/api/orders:create',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const orderCancel = <ThrowOnError extends boolean = false>(options: Options<OrderCancelData, ThrowOnError>) => (options.client ?? client).post<OrderCancelResponses, OrderCancelErrors, ThrowOnError>({
    url: '/api/orders:cancel',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const orderComplete = <ThrowOnError extends boolean = false>(options: Options<OrderCompleteData, ThrowOnError>) => (options.client ?? client).post<OrderCompleteResponses, OrderCompleteErrors, ThrowOnError>({
    url: '/api/orders:complete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const productSearch = <ThrowOnError extends boolean = false>(options?: Options<ProductSearchData, ThrowOnError>) => (options?.client ?? client).post<ProductSearchResponses, ProductSearchErrors, ThrowOnError>({
    url: '/api/products:search',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Display a listing of the resource
 */
export const productsIndex = <ThrowOnError extends boolean = false>(options?: Options<ProductsIndexData, ThrowOnError>) => (options?.client ?? client).get<ProductsIndexResponses, ProductsIndexErrors, ThrowOnError>({ url: '/api/products', ...options });

/**
 * Display the specified resource
 */
export const productsShow = <ThrowOnError extends boolean = false>(options: Options<ProductsShowData, ThrowOnError>) => (options.client ?? client).get<ProductsShowResponses, ProductsShowErrors, ThrowOnError>({ url: '/api/products/{product}', ...options });
