// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * CreateOrderRequest
 */
export type CreateOrderRequest = {
    items: Array<{
        extProductId: string;
    }>;
};

/**
 * InvoiceResource
 */
export type InvoiceResource = {
    id: string;
    externalId: string;
    subTotal: number;
    total: number;
    status: InvoiceStatus;
    createdAt: string | null;
    updatedAt: string | null;
};

/**
 * InvoiceStatus
 */
export type InvoiceStatus = 'pending' | 'paid' | 'cancelled' | 'refunded';

/**
 * OrderCollection
 */
export type OrderCollection = Array<OrderResource>;

/**
 * OrderDetailResource
 */
export type OrderDetailResource = {
    id: string;
    orderNumber: string;
    subTotal?: number;
    invoices?: Array<InvoiceResource>;
    orderItems?: Array<OrderItemResource>;
    createdAt: string | null;
    updatedAt: string | null;
};

/**
 * OrderItemResource
 */
export type OrderItemResource = {
    id: string;
    name: string;
    price: number;
    extProductId: string;
    createdAt: string | null;
    updatedAt: string | null;
};

/**
 * OrderResource
 */
export type OrderResource = {
    id: string;
    status: OrderStatus;
    invoiceId: string;
    subTotal?: number;
    createdAt: string | null;
    updatedAt: string | null;
};

/**
 * OrderStatus
 */
export type OrderStatus = 'abandoned' | 'locked' | 'warehouse' | 'delivered' | 'cancelled' | 'refunded';

/**
 * ProductCollection
 */
export type ProductCollection = Array<ProductResource>;

/**
 * ProductResource
 */
export type ProductResource = {
    id: string;
    name: string;
    description: string | null;
    price: number;
    createdAt: string | null;
    updatedAt: string | null;
};

/**
 * SearchProductsRequest
 */
export type SearchProductsRequest = {
    page?: number | null;
    perPage?: number | null;
    sortBy?: string | null;
    ids?: Array<string> | null;
};

export type OrdersIndexData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | null;
        perPage?: number | null;
        sortBy?: string | null;
    };
    url: '/api/orders';
};

export type OrdersIndexErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type OrdersIndexError = OrdersIndexErrors[keyof OrdersIndexErrors];

export type OrdersIndexResponses = {
    /**
     * Paginated set of `OrderResource`
     */
    200: {
        data: OrderCollection;
        links: {
            first: string | null;
            last: string | null;
            prev: string | null;
            next: string | null;
        };
        meta: {
            current_page: number;
            from: number | null;
            last_page: number;
            /**
             * Generated paginator links.
             */
            links: Array<{
                url: string | null;
                label: string;
                active: boolean;
            }>;
            /**
             * Base path for paginator generated URLs.
             */
            path: string | null;
            /**
             * Number of items shown per page.
             */
            per_page: number;
            /**
             * Number of the last item in the slice.
             */
            to: number | null;
            /**
             * Total number of items being paginated.
             */
            total: number;
        };
    };
};

export type OrdersIndexResponse = OrdersIndexResponses[keyof OrdersIndexResponses];

export type OrdersStoreData = {
    body: CreateOrderRequest;
    path?: never;
    query?: never;
    url: '/api/orders';
};

export type OrdersStoreErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type OrdersStoreError = OrdersStoreErrors[keyof OrdersStoreErrors];

export type OrdersStoreResponses = {
    /**
     * `OrderDetailResource`
     */
    200: {
        data: OrderDetailResource;
    };
};

export type OrdersStoreResponse = OrdersStoreResponses[keyof OrdersStoreResponses];

export type OrdersShowData = {
    body?: never;
    path: {
        orderId: string;
    };
    query?: never;
    url: '/api/orders/{orderId}';
};

export type OrdersShowResponses = {
    /**
     * `OrderDetailResource`
     */
    200: {
        data: OrderDetailResource;
    };
};

export type OrdersShowResponse = OrdersShowResponses[keyof OrdersShowResponses];

export type ProductSearchData = {
    body?: SearchProductsRequest;
    path?: never;
    query?: never;
    url: '/api/products:search';
};

export type ProductSearchErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ProductSearchError = ProductSearchErrors[keyof ProductSearchErrors];

export type ProductSearchResponses = {
    /**
     * Paginated set of `ProductResource`
     */
    200: {
        data: ProductCollection;
        links: {
            first: string | null;
            last: string | null;
            prev: string | null;
            next: string | null;
        };
        meta: {
            current_page: number;
            from: number | null;
            last_page: number;
            /**
             * Generated paginator links.
             */
            links: Array<{
                url: string | null;
                label: string;
                active: boolean;
            }>;
            /**
             * Base path for paginator generated URLs.
             */
            path: string | null;
            /**
             * Number of items shown per page.
             */
            per_page: number;
            /**
             * Number of the last item in the slice.
             */
            to: number | null;
            /**
             * Total number of items being paginated.
             */
            total: number;
        };
    };
};

export type ProductSearchResponse = ProductSearchResponses[keyof ProductSearchResponses];

export type ProductsIndexData = {
    body?: never;
    path?: never;
    query?: {
        page?: number | null;
        perPage?: number | null;
        sortBy?: string | null;
    };
    url: '/api/products';
};

export type ProductsIndexErrors = {
    /**
     * Validation error
     */
    422: {
        /**
         * Errors overview.
         */
        message: string;
        /**
         * A detailed description of each field that failed validation.
         */
        errors: {
            [key: string]: Array<string>;
        };
    };
};

export type ProductsIndexError = ProductsIndexErrors[keyof ProductsIndexErrors];

export type ProductsIndexResponses = {
    /**
     * Paginated set of `ProductResource`
     */
    200: {
        data: ProductCollection;
        links: {
            first: string | null;
            last: string | null;
            prev: string | null;
            next: string | null;
        };
        meta: {
            current_page: number;
            from: number | null;
            last_page: number;
            /**
             * Generated paginator links.
             */
            links: Array<{
                url: string | null;
                label: string;
                active: boolean;
            }>;
            /**
             * Base path for paginator generated URLs.
             */
            path: string | null;
            /**
             * Number of items shown per page.
             */
            per_page: number;
            /**
             * Number of the last item in the slice.
             */
            to: number | null;
            /**
             * Total number of items being paginated.
             */
            total: number;
        };
    };
};

export type ProductsIndexResponse = ProductsIndexResponses[keyof ProductsIndexResponses];

export type ProductsShowData = {
    body?: never;
    path: {
        /**
         * The product ID
         */
        product: string;
    };
    query?: never;
    url: '/api/products/{product}';
};

export type ProductsShowErrors = {
    /**
     * Not found
     */
    404: {
        /**
         * Error overview.
         */
        message: string;
    };
};

export type ProductsShowError = ProductsShowErrors[keyof ProductsShowErrors];

export type ProductsShowResponses = {
    /**
     * `ProductResource`
     */
    200: {
        data: ProductResource;
    };
};

export type ProductsShowResponse = ProductsShowResponses[keyof ProductsShowResponses];
