/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Drawer: typeof import('primevue/drawer')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductSkeleton: typeof import('./src/components/ProductSkeleton.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingCartDrawer: typeof import('./src/components/ShoppingCartDrawer.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const Button: typeof import('primevue/button')['default']
  const Card: typeof import('primevue/card')['default']
  const Drawer: typeof import('primevue/drawer')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
  const IconField: typeof import('primevue/iconfield')['default']
  const IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
  const Image: typeof import('primevue/image')['default']
  const InputIcon: typeof import('primevue/inputicon')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const OverlayBadge: typeof import('primevue/overlaybadge')['default']
  const ProductCard: typeof import('./src/components/ProductCard.vue')['default']
  const ProductSkeleton: typeof import('./src/components/ProductSkeleton.vue')['default']
  const ProgressSpinner: typeof import('primevue/progressspinner')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ShoppingCartDrawer: typeof import('./src/components/ShoppingCartDrawer.vue')['default']
  const Skeleton: typeof import('primevue/skeleton')['default']
  const TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  const Toolbar: typeof import('primevue/toolbar')['default']
  const WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
}